# http://www.appveyor.com/docs/appveyor-yml

#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 1.0.{build}

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
    - develop
    - master

#---------------------------------#
#    environment configuration    #
#---------------------------------#

init:
  - git config --global core.autocrlf input

cache:
  - '%APPDATA%\NuGet -> src\**\packages.config'

assembly_info:
  patch: true
  file: src\CommonAssemblyInfo.cs
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

#---------------------------------#
#       build configuration       #
#---------------------------------#

configuration: Release

build:
  project: src\CoreLogic.Wvs.sln
  verbosity: minimal

before_build:
  - nuget restore src\CoreLogic.Wvs.sln

after_build:
  - mkdir out
  - cd out
  - nuget pack "..\src\CoreLogic.Services.Wvs\CoreLogic.Services.Wvs.csproj" -Properties "Configuration=%CONFIGURATION%;Platform=AnyCPU" -IncludeReferencedProjects
  - ps: Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - cd ..

after_test:
  - ps: .\src\GenerateCodeCoverageReports.ps1

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: CodeCoverage

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:
  provider: NuGet
  api_key:
    secure: 0f8hc8T70O9EV5Yfmqv0oQqTsiAlK63m+I4IDGCRyYE5F4nVVa1efh9CYGolY3sR
  on:
    branch: master